### ISSUE TITLE
Wiki Saknar uppdateringar

### ISSUE THREAD

**Issue by Sydow75** [gosiacodes/vh-slut_vg#49]
Bra information på din Wiki sida men uppdatera gärna med korrekta filer, dvs all dokumentation som finns på projektet skall finnas på Wiki sidan. Återkoppla när det är klart så godkänner jag detta projekt.

**Comment by gosiacodes** [comment]
Tack för feedback Michaela! Uppdatering kommer lite senare, dokumentation är på gång.

**Comment by gosiacodes** [comment]
@Sydow75 Wiki är nu uppdaterad. Feedback required, så väntar jag för din feedback innan jag stänger issue.

**Comment by Sydow75** [comment]
Hej Riktigt bra jobbat @margareta75. Känner du dig nöjd kan du stänga issue.
