### ISSUE TITLE
Snart dags att lansera projektet!!

### ISSUE THREAD

**Issue by Sydow75** [gosiacodes/vh-slut_vg#51]
Nu är vi snart i mål med detta projekt. Bra jobbat, sidan funkar efter kontroll. Alla länkar funkar och layout är enligt kunds önskemål. Riktigt bra jobbat trots press från ledningen. :slightly_smiling_face:

**Comment by gosiacodes** [comment]
Tack Michaela! @Sydow75 Och tack för feedback. När projektet är helt avslutat, ska vi fira det tillsammans 😄

**Comment by Sydow75** [comment]
Underbart. Det gör vi. Ps notis funkar att du taggat mig :). Bra vi testade.
