### ISSUE TITLE
Bra jobbat!

### ISSUE THREAD

**Issue by nathaliedpettersson** [gosiacodes/vh-slut_vg#53]
Jag kan se att Gosia inte är helt ny på detta. Wiki-sidan och readme-filen är både informativ och fin att se på. 
Hon har comittat ofta och skapat många brancher. 

En sak jag reagerat på är alla pull request, är nyfiken på vad dem har för syfte när koden har gjorts ensam?

**Comment by gosiacodes** [comment]
Tack Nathalie @nathaliedpettersson för din feedback! När det gäller pull request för mig är det lättare att ha kontrol över projektet när jag måste sammanfoga branches än när jag gör merge direkt i GitHub Desktop (och tränade lite extra på det också, samt "låtsades" att skicka pull request till någon annan 😉 ). Ser fram emot att vi kan äntligen fira projektets avslutning! 🥳
